// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.EfCore;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250309193116_LoginUpdate")]
    partial class LoginUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.AssignRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("AssignRole");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Id = "c3e6e898-9e59-4402-90a8-264b96e6ecfa",
                            RoleName = "Admin",
                            UserId = "3"
                        },
                        new
                        {
                            RoleId = 2,
                            Id = "76f9d345-5eef-439a-a507-6b95b6f20a21",
                            RoleName = "Librarian",
                            UserId = "2"
                        });
                });

            modelBuilder.Entity("Entities.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRented")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "F. Scott Fitzgerald",
                            CategoryId = 1,
                            DatePublished = new DateTime(1925, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A novel set in the 1920s.",
                            IsRented = false,
                            Title = "The Great Gatsby",
                            TotalPages = 180
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Yuval Noah Harari",
                            CategoryId = 2,
                            DatePublished = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A book about the history of humankind.",
                            IsRented = false,
                            Title = "Sapiens: A Brief History of Humankind",
                            TotalPages = 443
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Stephen Hawking",
                            CategoryId = 3,
                            DatePublished = new DateTime(1988, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A popular-science book on cosmology.",
                            IsRented = false,
                            Title = "A Brief History of Time",
                            TotalPages = 256
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Anne Frank",
                            CategoryId = 4,
                            DatePublished = new DateTime(1947, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The diary of a Jewish girl during World War II.",
                            IsRented = false,
                            Title = "The Diary of a Young Girl",
                            TotalPages = 283
                        });
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Fiction"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Non-Fiction"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Science"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "History"
                        });
                });

            modelBuilder.Entity("Entities.Models.Rental", b =>
                {
                    b.Property<int>("RentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RentalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RentId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            RentId = 1,
                            BookId = 1,
                            IsApproved = true,
                            RentalDate = new DateTime(2025, 3, 9, 22, 31, 16, 324, DateTimeKind.Local).AddTicks(4927),
                            UserId = "1"
                        },
                        new
                        {
                            RentId = 2,
                            BookId = 2,
                            IsApproved = true,
                            RentalDate = new DateTime(2025, 3, 9, 22, 31, 16, 324, DateTimeKind.Local).AddTicks(4946),
                            UserId = "2"
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "019b829e-e389-44f0-aa9c-a4f0bd741830",
                            Email = "john.doe@example.com",
                            EmailConfirmed = true,
                            FullName = "John Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.DOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHN.DOE",
                            PasswordHash = "AQAAAAIAAYagAAAAEKQaeWl34Na0XT17aK7zv3l2sgPOxmmLSBL7CskCjIC7oOvn71IY4iU3afnnPYhy1Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "stamp_1",
                            TwoFactorEnabled = false,
                            UserName = "john.doe"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8d459a93-8007-43fa-8e07-98d646d86695",
                            Email = "librarian@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Jane Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "LIBRARIANH@GMAIL.COM",
                            NormalizedUserName = "JANE.SMITH",
                            PasswordHash = "AQAAAAIAAYagAAAAEHmLFPld3FeBSpuqcv+AAxze+GpBTUK5XbA3UPH/GHNkeM8ixF/K0unKY588dXEcWw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "stamp_2",
                            TwoFactorEnabled = false,
                            UserName = "librarian"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ea8e2d0a-cf1b-4bf4-aa82-b4de50cf675e",
                            Email = "efeaydeskin@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Efe Aydeskin",
                            LockoutEnabled = false,
                            NormalizedEmail = "EFEAYDESKIN@GMAIL.COM",
                            NormalizedUserName = "EFE.AYDESKIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEKawWHufIHPW1/H/aSJzG2c/CMh8sLQaFgIM/XJk92qVkkwSCG7Ri1M+RTyWc9a0bA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "stamp_3",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Entities.Models.Book", b =>
                {
                    b.HasOne("Entities.Models.Category", "Categories")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Entities.Models.Rental", b =>
                {
                    b.HasOne("Entities.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
